strings = {
    "CHAR_LEVEL_UP": "R) YARRR! R) The following crew are now a {ranktitle}: {names}",
    "FOLLOW_WELCOME": "Welcome to our new Crewmembers: {names}! Have some welcome capnBooty ! R)",
    "TIP_MESSAGE": "{name} has tipped ${amount} {to}! Give them some love!!!",
    "SUB_WELCOME": "Welcome new Subs and Resubs: {names}! Have some capnBooty! R)",
    "CMD_BET_PRIZE_POOL": "Betting has ended! Total prize pool: {amount} doubloons!",
    "CMD_BOOTY_AMOUNT": "{name} you have {amount} doubloons!",
    "CMD_BOOTY_NONE": "Sorry {name}, you have no booty capnFeels",
    "CMD_BOOTY_BUFFERED": "Booty amounts: {amounts}",
    "CMD_GIVE_SENT": "{amount} doubloons sent to {recipient}! Thanks {sender}!",
    "CMD_GIVE_SELF": "You can't send money to yourself!",
    "CMD_GIVE_INVALID": "Sorry {sender}, that isn't a valid amount.",
    "CMD_GIVE_INSUFFICIENT": "Sorry {sender}, you don't have enough booty for that.",
    "CMD_GIVE_MISSING": "Sorry, {recipient} isn't here...",
    "CMD_GIVE_USAGE": "To send money use: !give [name] [amount], e.g. !give capn_flint 50",
    "CMD_TOP_HIGHEST": "The highest ranked Pirate on the ship is {name}!",
    "CMD_TOP_NONE": "No pirates aboard sir!",
    "CMD_TOPBOOTY_HIGHEST": "The richest pirate on the ship be {name} with {amount} doubloons!",
    
}
